
name: Android CI with Firebase and Maps Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Decode google-services.json from secret
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

    - name: Decode secrets.xml from secret
      run: |
        mkdir -p app/src/main/res/values
        echo "${{ secrets.GOOGLE_MAPS_SECRET_XML }}" | base64 -d > app/src/main/res/values/secrets.xml

    - name: Build the project with warnings
      run: ./gradlew build --warning-mode all --stacktrace

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
