name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Generate dummy google-services.json
      run: |
        mkdir -p app
        cat > app/google-services.json <<EOF
        {
          "project_info": {
            "project_number": "000000000000",
            "firebase_url": "https://dummy.firebaseio.com",
            "project_id": "dummy",
            "storage_bucket": "dummy.appspot.com"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                "android_client_info": {
                  "package_name": "com.example.hervoice"
                }
              },
              "api_key": [
                {
                  "current_key": "dummy_key"
                }
              ]
            }
          ]
        }
        EOF

    - name: Build the project with warnings
      run: ./gradlew build --warning-mode all --stacktrace
